### ISSUE TITLE
Won't Follow Google News Redirects

### ISSUE THREAD

**Issue by tokyojimu** [eafer/rdrview#11]
Hi. I'm helping a blind friend who uses rdrview to read articles. It seems to follow some, but not all, redirects. In particular, Google News URLs don't work. Here's an example:

https://www.google.com/url?rct=j&sa=t&url=https://www.intellinews.com/turkey-s-karel-telco-equipment-maker-buys-local-peer-telesis-for-0-5mn-198953/%3Fsource%3Dcee-telecoms-media-it-newswatch&ct=ga&cd=CAEYASoUMTM2MzQwNzExNDcyNTAyMzUwMzMyGjg1NDM3YjRkY2FmN2QyZGE6Y29tOmVuOlVT&usg=AFQjCNH-3gYzxzSXyPZLrWczutgjqq3kag

rdrview reports "rdrview: document has no body tag".

**Comment by eafer** [comment]
> It seems to follow some, but not all, redirects. In particular, Google News URLs don't work.

Thanks for the report. Those are HTML redirects, not HTTP redirects, so curl
can't handle them. I just pushed a series of patches for this problem, let
me know if they work for you. The url you linked to still won't look right,
because of the paywall.

**Comment by eafer** [comment]
I believe this issue is solved, feel free to reopen if you disagree.
