### ISSUE TITLE
error while loading shared libraries: libicui18n.so.67

### ISSUE THREAD

**Issue by muralikodali** [eafer/rdrview#13]
My OS is Arch Linux. I have recently upgraded my system.

rdrview is giving following error while starting :  

```
rdrview: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory
```

/usr/lib is showing  libicui18n.so.68

**Comment by parkerlreed** [comment]
Just rebuild from AUR. It will compile against the newer lib

**Comment by muralikodali** [comment]
thanks. problem solved.
