### ISSUE TITLE
Musl 1.2.2 requires --disable-sandbox

### ISSUE THREAD

**Issue by sdsddsd1** [eafer/rdrview#20]
Hello,
latest `master` requires the sandbox to be disabled on my musl system.

**Comment by eafer** [comment]
> latest `master` requires the sandbox to be disabled on my musl system.

Thanks for the report. Try running:

  strace -f rdrview -H 'https://github.com/eafer/rdrview' 2>&1 >/dev/null | grep EPERM

and send me the output. That should tell us which syscalls are getting
blocked.

**Comment by sdsddsd1** [comment]
Here you go:
```
[pid 24984] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 EPERM (Operation not permitted)
[pid 24984] rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], 0x7ffff841abd0, 8) = -1 EPERM (Operation not permitted)
[pid 24984] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = -1 EPERM (Operation not permitted)

```

**Comment by eafer** [comment]
> [pid 24984] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 EPERM (Operation not permitted)

I just pushed a patch to allow mmap(), let me know if it helps.

**Comment by sdsddsd1** [comment]
This was fast. It does work now again. Thank you!
