### ISSUE TITLE
Umlauts not displayed through rdrview

### ISSUE THREAD

**Issue by sdsddsd1** [eafer/rdrview#21]
Umlauts are displayed as fragments when a page is extracted through rdrview.
Example: https://www.heise.de/news/Abschaltungen-von-Mining-Farmen-in-China-Gefahr-oder-Chance-fuer-Bitcoin-6160001.html  
In my`.mailcap` is
```
text/html; /usr/local/bin/lynx --dump %s; copiousoutput; description=HTML Text; nametemplate=%s.html
```

Snippet in rdrview:
```
...KryptowÃ¤hrung, die anfÃ¤llig fÃ¼r eine...
```
  

Snippet through lynx --dump:
```
...Kryptowährung, die anfällig für eine 51-Prozent...
```

**Comment by eafer** [comment]
I failed to reproduce. I seem to recall an encoding problem with old versions of lynx, which version are you using? I'm on 2.9.0dev.6.

**Comment by sdsddsd1** [comment]
Apologies, I have missed your response.
My lynx version is `2.8.9rel.1`. I have to try a later version.
I have tested with w3m `0.5.` and the umlauts are displayed correctly.

**Comment by sdsddsd1** [comment]
Lynx version 2.9.0.dev.6 displays the umlauts in the correct way. So it seems to be a problem with lynx. As mentioned w3m also works correctly. Closing, thx!
