### ISSUE TITLE
Question: Does rdrview also support images?

### ISSUE THREAD

**Issue by dorneanu** [eafer/rdrview#22]
Hi! First of all: Awesome tool. I use it to extract readable part from URLs and convert that to epub (see [blog post](http://blog.dornea.nu/2021/08/15/howto-convert-pocket-reader-links-to-epub-and-upload-to-dropbox/#read-later-on-e-reader)). 

However: In my epub's I somehow miss pictures. I haven't investigated yet (might be `pandoc`s fault) but could it be that `rdrview` filters out images?

Cheers,
Victor

**Comment by eafer** [comment]
> First of all: Awesome tool. I use it to extract readable part from URLs and convert that to epub

Thanks! I'm glad that you like it.

> I've just found rdrview does actually include img tags but when converting the HTML to epub (using pandoc) the images are gone.

I'm not sure I understand the problem. I've never used pandoc myself, but if you set the `--self-contained` option when working with the output of rdrview, shouldn't pandoc retrieve the images itself?

**Comment by dorneanu** [comment]
Yes, you're right. pandoc retrieves the images by itself. No need to add this to rdrview. Sorry for the confusion.

I'll close this one.
