### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by tathastu871** [eafer/rdrview#26]
./rdrview -B lynx 'https://github.com/eafer/rdrview'
no output
lynx w3m links elinks netsurf nothing works 
Termux
Only rdview -H url | w3m -dump works 
no other browser
-B browser option doesn't work at all

**Comment by mglh** [comment]
I cannot confirm this error.
I did a git pull on my Debian amd64 system and compiled the code.
That executable appears to be working fine.

**Comment by eafer** [comment]
I think this issue was about building in Termux for Android. I had not replied yet because I know nothing of Termux and I had not found the time to look into it. But since @tathastu871 closed it himself, I guess it doesn't matter anymore.
