### ISSUE TITLE
Handle local content

### ISSUE THREAD

**Issue by Seirdy** [eafer/rdrview#27]
rdrview is great for viewing remote content, but it'd be great to handle local content. The ability to read standard input or a file would be appreciated.

**Comment by eafer** [comment]
> rdrview is great for viewing remote content, but it'd be great to handle local content. The ability to read standard input or a file would be appreciated.

It can do both already. You can request a local path instead of a url, and
you don't provide either it will read standard input. The details are
explained in the man page.

**Comment by Seirdy** [comment]
On Mon, Feb 14, 2022 at 07:01:22AM -0800, Ernesto Fernández wrote:
>It can do both already. You can request a local path instead of a url, 
>and
>you don't provide either it will read standard input. The details are
>explained in the man page.

Apologies; I got this mixed up with the Mercury Parser CLI tool. I'll 
file an issue there.

-- 
/Seirdy
