### ISSUE TITLE
Option to keep class attributes in the processed HTML

### ISSUE THREAD

**Issue by michal-h21** [eafer/rdrview#36]
I've created an application that converts [web pages to PDF using LuaLaTeX](https://github.com/michal-h21/rmodepdf). It uses `rdrview` to clean-up the HTML code before passing it to Lua post-processing. Users can use Lua scripts to change the way how various HTML elements are transformed to LaTeX. These transformation functions support CSS selectors to apply rules. Quite ofthen, you will want to apply some specific styles to elements with particular classes, but I've found that `rdrview` removes `class` attributes from the generated HTML. 

I've found this [comment in the source code](https://github.com/eafer/rdrview/blob/30cb8782afeae5b15c7026d9f7801f3ceb330a62/src/readability.c#L1666):

>  * fx: Removes the class="" attribute [...], except those that match
>  * CLASSES_TO_PRESERVE and the classesToPreserve array from the options object.
>  *
>  * TODO: add cli option to preserve other classes, or all of them

So my question is: would it be possible to add cli option to preserve all classes? It would be really useful for my use case.

**Comment by michal-h21** [comment]
Sounds great, thanks!

**Comment by eafer** [comment]
I just tagged a release that adds a `--preserve-classes` option. When you can let me know if it helps.

**Comment by michal-h21** [comment]
This is exactly what I needed, thanks! It works perfectly.
