### ISSUE TITLE
User Agent -- How to set?

### ISSUE THREAD

**Issue by mglh** [eafer/rdrview#5]
Is it possible to set the User Agent rdrview transfers to the HTML server?
Some HTML servers refuse to deliver a page to curl when it is using its native User Agent.
As far as I understand, this concerns also libcurl.

**Comment by eafer** [comment]
> Some HTML servers refuse to deliver a page to curl when it is using its native User Agent.

I've seen this problem with pages behind Incapsula, so we don't use curl's
default user agent string anymore; we send "Mozilla/5.0 rdrview/0.1"
instead.

> Is it possible to set the User Agent rdrview transfers to the HTML server?

I guess I can add an option for that, though I don't like to overcomplicate
the interface. Can you share the urls for the pages that are failing? Maybe
I can find a simpler solution.

**Comment by mglh** [comment]
This one caught my eye:
https://www.wetteronline.de/wetterticker/0f7f88a0-0048-4327-aeed-b90c110097d3

I have to admit that the fact that this page is not delivered to curl may not be the problem itself; meanwhile I have realized that even Firefox doesn't offer its reader view for it, so rdrview may not be able to process it, too.

**Comment by eafer** [comment]
> This one caught my eye:
> https://www.wetteronline.de/wetterticker/0f7f88a0-0048-4327-aeed-b90c110097d3
> 
> I have to admit that the fact that this page is not delivered to curl may not be the problem itself; meanwhile I have realized that even Firefox doesn't offer its reader view for it, so rdrview may not be able to process it, too.

Right, the problem for this page is that the html has no actual "content"
that we can extract: the article is fetched later, via javascript. Changing
the user agent won't help.

**Comment by eafer** [comment]
I'm closing this for now, but feel free to reopen if you find another example.
