### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by communistkiro** [eafer/rdrview#8]
## the problem
Various glyphs get rendered in strange ways, comparing the piped-to-less content with the `--html` dump option:
’  as `<E2>`
… as `<E2><A6>`
ł as `<C5>`
▲ as `<E2><B2>`
and likely many more.

These appear highlighted within `less`, or as � if not piped. `lynx -dump -nolist URL` renders nearly everything.

## step to reproduce
at least on my setup:
1. make install rdrview
2. rdrview -B 'lynx -dump -nolist' URL | less; 

the URL must contain an apostrophe ' (which for some reason gets converted to ’, same goes for an three sequential periods ..., which get transformed to an ellipsis.

I'm unsure if the problem is in the encoding, or something else.

**Comment by eafer** [comment]
Thank you for the report.

> Various glyphs get rendered in strange ways, comparing the piped-to-less content with the `--html` dump option:

Rdrview doesn't do its own rendering, so if the html dump looks correct the
problem is likely with your browser.

> These appear highlighted within `less`, or as � if not piped.

I think I've seen this problem before, with an old version of lynx. Are you
using the latest? Can you check what happens with another browser?

> ## step to reproduce
> at least on my setup:
> 1. make install rdrview
> 2. rdrview -B 'lynx -dump -nolist' URL | less; 
> 
> the URL must contain an apostrophe ' (which for some reason gets converted to ’, same goes for an three sequential periods ..., which get transformed to an ellipsis.

That sounds really strange. I failed to reproduce with your instructions
alone, could you give me a specific url where you notice this issue?

**Comment by communistkiro** [comment]
lynx is `Version 2.8.9rel.1 (08 Jul 2018)`

Renders correctly: https://github.com/eafer/rdrview/, as does https://www.vincentntang.com/wtf-are-jamstack-apps-and-statiac-site-generators/ Although both use normal apostrophe, not the slanted one.

These don't: https://gamehistory.org/monkeyisland/, https://en.wikipedia.org/wiki/Clebsch%E2%80%93Gordan_coefficients [screenshot](https://www63.zippyshare.com/v/KLs4SRWn/file.html
)

I'm using st as a terminal emulator with Fira Code as a font. 

Using firefox as the browser fails, as the temp output file gets deleted for some reason.. I remember when I first found rdrview it wasn't like that. Regardless, I use it with a feed reader in terminal mostly, launching a new browser instance or tab seemed moot, so I went for the dump option.

**Comment by eafer** [comment]
On Sun, Nov 29, 2020 at 05:45:57PM -0800, vlg wrote:
> lynx is `Version 2.8.9rel.1 (08 Jul 2018)`

I'm using 2.9.0dev.5 (27 Feb 2020); my bet is still on a lynx bug, though I
can't find anything about it in the changelog or mailing lists. It looks
like it's discarding some bytes from these utf8 sequences, so less can't
decode them and just prints the numbers.

Did you say before that you tried to dump these pages with lynx directly,
without going through rdrview? If I'm right I would expect that to fail as
well.

> Using firefox as the browser fails, as the temp output file gets deleted for some reason..

Odd, it works for me. Thanks for mentioning that, it may be important. Is
it possible that your firefox process launches in the background?

To test lynx, you can still dump the html to a file, and later open it with
firefox; or try another text browser (links, w3m, elinks). I'll try your
version of lynx myself once I have the time.

**Comment by communistkiro** [comment]
> Odd, it works for me. Thanks for mentioning that, it may be important. Is it possible that your firefox process launches in the background?

I do `rdrview -B firefox URL`, and I get a visual bell for the workspace where firefox is at. It just now worked, my pc was asleep, from yesterday, and for the first link it work, and for all afterword I get 'Firefox can’t find the file at /tmp/jIAKnb/output.html.', only with different rnd name. I believe it may be a background thing, nothing on my part.

> Did you say before that you tried to dump these pages with lynx directly, without going through rdrview? If I'm right I would expect that to fail as well.

Solo lynx dumps work nigh perfectly, only `<B7>` doesn't render for the medium article, and a single `<BB>` for the monkey island history one. This is why I though rdrview might be culpable. **However...**

Removing the `-dump` opt for lynx results in correct rendition of all glyphs within the lynx for all of the above pages. The files don't get deleted before lynx has a chance to open them, too.

elinks renders properly; elinks with `-dump 1`  renders properly, as do links with and without the option.

I might just switch the command to use elinks, this seems to not be an rdrview issue.

**Comment by eafer** [comment]
> I do `rdrview -B firefox URL`, and I get a visual bell for the workspace where firefox is at. It just now worked, my pc was asleep, from yesterday, and for the first link it work, and for all afterword I get 'Firefox can’t find the file at /tmp/jIAKnb/output.html.', only with different rnd name. I believe it may be a background thing, nothing on my part.

Oh, I get it. The first time you run the firefox command, it stays open as
long as the browser itself, but the second time it just sends the url to the
existing browser instance and exits. So rdrview itself exits and cleans up
its files before firefox can open the page.

This looks tricky to fix, but I'll see what I can do.

> Solo lynx dumps work nigh perfectly, only `<B7>` doesn't render for the medium article, and a single `<BB>` for the monkey island history one. This is why I though rdrview might be culpable. **However...**
> 
> Removing the `-dump` opt for lynx results in correct rendition of all glyphs within the lynx for all of the above pages. The files don't get deleted before lynx has a chance to open them, too.
> 
> elinks renders properly; elinks with `-dump 1`  renders properly, as do links with and without the option.
> 
> I might just switch the command to use elinks, this seems to not be an rdrview issue.

The rdrview output is not a full html document, it's just a single element,
so it doesn't report its encoding. I'm thinking that older versions of lynx
may not always assume utf-8, which would explain why rdrview is treated
differently, but not why the problem is only for the dumps, or why it
drops some bytes. So yes, a bug on lynx is likely; but maybe I should output
a full valid document to prevent problems like this.

**Comment by communistkiro** [comment]
Setting CHARACTER_SET:utf-8 in lynx.cfg makes ’ get rendered as â -- for somebody with more knowledge in glyph encoding could work out something from this info - how many bytes are dropped, is it the same with all..? 

From https://en.wikipedia.org/wiki/Ellipsis with lynx I get `The ellipsis ..., . . ., or (in Unicode) â¦, also known informally as`. There are a lot of charset, encoding, etc. options in lynx.cfg; it'd be a headache trying every permutation groping for a solution.

Regardless, thanks for suggesting trying elinks and links, I'd forgotten they had -dump options.
